### ISSUE TITLE
Use github-readme-stats

### ISSUE THREAD

**Issue by core-man** [seismo-learn/maintenance#15]
Since we will have more and more repos, I am thinking to use [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) so that we can display more repos.

**Comment by seisman** [comment]
It doesn't work for the organization account.

seisman:

![](https://github-readme-stats.vercel.app/api?username=seisman)

seismo-learn:

![](https://github-readme-stats.vercel.app/api?username=seismo-learn)

**Comment by core-man** [comment]
ggg
